---


- name: Configure Elasticsearch
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: "{{ item.handler }}"
  with_items:
    - { src: 'logstash.yml.j2', dest: '/etc/logstash/logstash.yml', handler: 'Restart Logstash'}
    - { src: 'logstash.service.j2', dest: '/etc/systemd/system/logstash.service', handler: 'Restart Logstash'}
    - { src: 'input.conf.j2', dest: '/etc/logstash/conf.d/input.conf', handler: 'Restart Logstash'}
    - { src: 'filter.conf.j2', dest: '/etc/logstash/conf.d/filter.conf', handler: 'Restart Logstash'}
    - { src: 'output.conf.j2', dest: '/etc/logstash/conf.d/output.conf', handler: 'Restart Logstash'}
