---

#  ElasticSearch Pre-Requisites Defaults

major_version: "7.x"
abosulte_version: "7.7.0"
public_key_url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
repo_definition: "deb https://artifacts.elastic.co/packages/{{major_version}}/apt stable main"

