---
- name: Configure Apache Kafka
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: "{{ item.handler }}"
  with_items:
    - { src: 'zookeeper.properties.j2', dest: '{{kafka_home}}/config/zookeeper.properties', handler: 'Restart Zookeeper'}
    - { src: 'kafka-server.properties.j2', dest: '{{kafka_home}}/config/server.properties', handler: 'Restart Kafka'}
    - { src: 'kafka.service.j2', dest: '/etc/systemd/system/kafka.service', handler: 'Reload Systemd'}
    - { src: 'zookeeper.service.j2', dest: '/etc/systemd/system/zookeeper.service', handler: 'Reload Systemd'}



