---
# Install elasticsearch
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

# Mark Elasticsearch to avoid accidental upgrades
- name: Mark hold to elasticsearch
  shell: apt-mark hold elasticsearch
