---      
- name: Install Elasticsearch {{ abosulte_version }}
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Mark hold to elasticsearch
  shell: apt-mark hold elasticsearch
      
...
